/* Flag library — auto-generated from SVG filenames */
/* global FlagsData */
// eslint-disable-next-line no-unused-vars
var FlagsData = [
  { name: "Afghanistan", code: "AFG", file: "Afghanistan (AFG).svg" },
  { name: "Aland Islands", code: "ALA", file: "Aland Islands (ALA).svg" },
  { name: "Albania", code: "ALB", file: "Albania (ALB).svg" },
  { name: "Algeria", code: "DZA", file: "Algeria (DZA).svg" },
  { name: "American Samoa", code: "ASM", file: "American Samoa (ASM).svg" },
  { name: "Andorra", code: "AND", file: "Andorra (AND).svg" },
  { name: "Angola", code: "AGO", file: "Angola (AGO).svg" },
  { name: "Anguilla", code: "AIA", file: "Anguilla (AIA).svg" },
  { name: "Antigua and Barbuda", code: "ATG", file: "Antigua and Barbuda (ATG).svg" },
  { name: "Argentina", code: "ARG", file: "Argentina (ARG).svg" },
  { name: "Armenia", code: "ARM", file: "Armenia (ARM).svg" },
  { name: "Aruba", code: "ABW", file: "Aruba (ABW).svg" },
  { name: "Australia", code: "AUS", file: "Australia (AUS).svg" },
  { name: "Austria", code: "AUT", file: "Austria (AUT).svg" },
  { name: "Azerbaijan", code: "AZE", file: "Azerbaijan (AZE).svg" },
  { name: "Bahamas", code: "BHS", file: "Bahamas (BHS).svg" },
  { name: "Bahrain", code: "BHR", file: "Bahrain (BHR).svg" },
  { name: "Bangladesh", code: "BGD", file: "Bangladesh (BGD).svg" },
  { name: "Barbados", code: "BRB", file: "Barbados (BRB).svg" },
  { name: "Basque", code: "", file: "Basque.svg" },
  { name: "Belarus", code: "BLR", file: "Belarus (BLR).svg" },
  { name: "Belgium", code: "BEL", file: "Belgium (BEL).svg" },
  { name: "Belize", code: "BLZ", file: "Belize (BLZ).svg" },
  { name: "Benin", code: "BEN", file: "Benin (BEN).svg" },
  { name: "Bermuda", code: "BMU", file: "Bermuda (BMU).svg" },
  { name: "Bhutan", code: "BTN", file: "Bhutan (BTN).svg" },
  { name: "Bolivia", code: "BOL", file: "Bolivia (BOL).svg" },
  { name: "Bosnia and Herzegovina", code: "BIH", file: "Bosnia and Herzegovina (BIH).svg" },
  { name: "Botswana", code: "BWA", file: "Botswana (BWA).svg" },
  { name: "Brazil", code: "BRA", file: "Brazil (BRA).svg" },
  { name: "British Indian Ocean Territory", code: "IOT", file: "British Indian Ocean Territory (IOT).svg" },
  { name: "British Virgin Islands", code: "VGB", file: "British Virgin Islands (VGB).svg" },
  { name: "Brunei Darussalam", code: "BRN", file: "Brunei Darussalam (BRN).svg" },
  { name: "Bulgaria", code: "BGR", file: "Bulgaria (BGR).svg" },
  { name: "Burkina Faso", code: "BFA", file: "Burkina Faso (BFA).svg" },
  { name: "Burundi", code: "BDI", file: "Burundi (BDI).svg" },
  { name: "Cabo Verde", code: "CPV", file: "Cabo Verde (CPV).svg" },
  { name: "Cambodia", code: "KHM", file: "Cambodia (KHM).svg" },
  { name: "Cameroon", code: "CMR", file: "Cameroon (CMR).svg" },
  { name: "Canada", code: "CAN", file: "Canada (CAN).svg" },
  { name: "Catalonia", code: "", file: "Catalonia.svg" },
  { name: "Cayman Islands", code: "CYM", file: "Cayman Islands (CYM).svg" },
  { name: "Central African Republic", code: "CAF", file: "Central African Republic (CAF).svg" },
  { name: "Chad", code: "TCD", file: "Chad (TCD).svg" },
  { name: "Chile", code: "CHL", file: "Chile (CHL).svg" },
  { name: "China", code: "CHN", file: "China (CHN).svg" },
  { name: "China - Hong Kong", code: "HKG", file: "China - Hong Kong (HKG).svg" },
  { name: "China - Macau", code: "MAC", file: "China - Macau (MAC).svg" },
  { name: "China - Taiwan Province", code: "TWN", file: "China - Taiwan Province (TWN).svg" },
  { name: "Christmas Island", code: "CXR", file: "Christmas Island (CXR).svg" },
  { name: "Cocos (Keeling) Islands", code: "CCK", file: "Cocos (Keeling) Islands (CCK).svg" },
  { name: "Colombia", code: "COL", file: "Colombia (COL).svg" },
  { name: "Comoros", code: "COM", file: "Comoros (COM).svg" },
  { name: "Congo", code: "COG", file: "Congo (COG).svg" },
  { name: "Cook Islands", code: "COK", file: "Cook Islands (COK).svg" },
  { name: "Costa Rica", code: "CRI", file: "Costa Rica (CRI).svg" },
  { name: "Côte d'Ivoire", code: "CIV", file: "Côte d'Ivoire (CIV).svg" },
  { name: "Croatia", code: "HRV", file: "Croatia (HRV).svg" },
  { name: "Cuba", code: "CUB", file: "Cuba (CUB).svg" },
  { name: "Curaçao", code: "CUW", file: "Curaçao (CUW).svg" },
  { name: "Cyprus", code: "CYP", file: "Cyprus (CYP).svg" },
  { name: "Czechia", code: "CZE", file: "Czechia (CZE).svg" },
  { name: "Democratic People's Republic of Korea", code: "PRK", file: "Democratic People's Republic of Korea (PRK).svg" },
  { name: "Democratic Republic of the Congo", code: "COD", file: "Democratic Republic of the Congo (COD).svg" },
  { name: "Denmark", code: "DNK", file: "Denmark (DNK).svg" },
  { name: "Djibouti", code: "DJI", file: "Djibouti (DJI).svg" },
  { name: "Dominica", code: "DMA", file: "Dominica (DMA).svg" },
  { name: "Dominican Republic", code: "DOM", file: "Dominican Republic (DOM).svg" },
  { name: "Ecuador", code: "ECU", file: "Ecuador (ECU).svg" },
  { name: "Egypt", code: "EGY", file: "Egypt (EGY).svg" },
  { name: "El Salvador", code: "SLV", file: "El Salvador (SLV).svg" },
  { name: "Equatorial Guinea", code: "GNQ", file: "Equatorial Guinea (GNQ).svg" },
  { name: "Eritrea", code: "ERI", file: "Eritrea (ERI).svg" },
  { name: "Estonia", code: "EST", file: "Estonia (EST).svg" },
  { name: "Eswatini", code: "SWZ", file: "Eswatini (SWZ).svg" },
  { name: "Ethiopia", code: "ETH", file: "Ethiopia (ETH).svg" },
  { name: "European Union", code: "", file: "European Union.svg" },
  { name: "Falkland Islands", code: "FLK", file: "Falkland Islands (FLK).svg" },
  { name: "Faroe Islands", code: "FRO", file: "Faroe Islands (FRO).svg" },
  { name: "Fiji", code: "FJI", file: "Fiji (FJI).svg" },
  { name: "Finland", code: "FIN", file: "Finland (FIN).svg" },
  { name: "Flanders", code: "", file: "Flanders.svg" },
  { name: "France", code: "FRA", file: "France (FRA).svg" },
  { name: "French Polynesia", code: "PYF", file: "French Polynesia (PYF).svg" },
  { name: "French Southern Territories", code: "ATF", file: "French Southern Territories (ATF).svg" },
  { name: "Gabon", code: "GAB", file: "Gabon (GAB).svg" },
  { name: "Gambia", code: "GMB", file: "Gambia (GMB).svg" },
  { name: "Georgia", code: "GEO", file: "Georgia (GEO).svg" },
  { name: "Germany", code: "DEU", file: "Germany (DEU).svg" },
  { name: "Ghana", code: "GHA", file: "Ghana (GHA).svg" },
  { name: "Gibraltar", code: "GIB", file: "Gibraltar (GIB).svg" },
  { name: "Greece", code: "GRC", file: "Greece (GRC).svg" },
  { name: "Greenland", code: "GRL", file: "Greenland (GRL).svg" },
  { name: "Grenada", code: "GRD", file: "Grenada (GRD).svg" },
  { name: "Guam", code: "GUM", file: "Guam (GUM).svg" },
  { name: "Guatemala", code: "GTM", file: "Guatemala (GTM).svg" },
  { name: "Guernsey", code: "GGY", file: "Guernsey (GGY).svg" },
  { name: "Guinea", code: "GIN", file: "Guinea (GIN).svg" },
  { name: "Guinea-Bissau", code: "GNB", file: "Guinea-Bissau (GNB).svg" },
  { name: "Guyana", code: "GUY", file: "Guyana (GUY).svg" },
  { name: "Haiti", code: "HTI", file: "Haiti (HTI).svg" },
  { name: "Holy See", code: "VAT", file: "Holy See (VAT).svg" },
  { name: "Honduras", code: "HND", file: "Honduras (HND).svg" },
  { name: "Hungary", code: "HUN", file: "Hungary (HUN).svg" },
  { name: "Hyogo Prefecture  - Japan", code: "", file: "Hyogo Prefecture  - Japan.svg" },
  { name: "Iceland", code: "ISL", file: "Iceland (ISL).svg" },
  { name: "India", code: "IND", file: "India (IND).svg" },
  { name: "Indonesia", code: "IDN", file: "Indonesia (IDN).svg" },
  { name: "International Maritime Organization", code: "", file: "International Maritime Organization.svg" },
  { name: "Iran", code: "IRN", file: "Iran (IRN).svg" },
  { name: "Iraq", code: "IRQ", file: "Iraq (IRQ).svg" },
  { name: "Ireland", code: "IRL", file: "Ireland (IRL).svg" },
  { name: "Isle of Man", code: "IMN", file: "Isle of Man (IMN).svg" },
  { name: "Israel", code: "ISR", file: "Israel (ISR).svg" },
  { name: "Italy", code: "ITA", file: "Italy (ITA).svg" },
  { name: "Jamaica", code: "JAM", file: "Jamaica (JAM).svg" },
  { name: "Japan", code: "JPN", file: "Japan (JPN).svg" },
  { name: "Jersey", code: "JEY", file: "Jersey (JEY).svg" },
  { name: "Jordan", code: "JOR", file: "Jordan (JOR).svg" },
  { name: "Kazakhstan", code: "KAZ", file: "Kazakhstan (KAZ).svg" },
  { name: "Kenya", code: "KEN", file: "Kenya (KEN).svg" },
  { name: "Kiribati", code: "KIR", file: "Kiribati (KIR).svg" },
  { name: "Kuwait", code: "KWT", file: "Kuwait (KWT).svg" },
  { name: "Kyrgyzstan", code: "KGZ", file: "Kyrgyzstan (KGZ).svg" },
  { name: "Lao People's Democratic Republic", code: "LAO", file: "Lao People's Democratic Republic (LAO).svg" },
  { name: "Latvia", code: "LVA", file: "Latvia (LVA).svg" },
  { name: "Lebanon", code: "LBN", file: "Lebanon (LBN).svg" },
  { name: "Lesotho", code: "LSO", file: "Lesotho (LSO).svg" },
  { name: "Liberia", code: "LBR", file: "Liberia (LBR).svg" },
  { name: "Libya", code: "LBY", file: "Libya (LBY).svg" },
  { name: "Liechtenstein", code: "LIE", file: "Liechtenstein (LIE).svg" },
  { name: "Lithuania", code: "LTU", file: "Lithuania (LTU).svg" },
  { name: "Luxembourg", code: "LUX", file: "Luxembourg (LUX).svg" },
  { name: "Madagascar", code: "MDG", file: "Madagascar (MDG).svg" },
  { name: "Malawi", code: "MWI", file: "Malawi (MWI).svg" },
  { name: "Malaysia", code: "MYS", file: "Malaysia (MYS).svg" },
  { name: "Maldives", code: "MDV", file: "Maldives (MDV).svg" },
  { name: "Mali", code: "MLI", file: "Mali (MLI).svg" },
  { name: "Malta", code: "MLT", file: "Malta (MLT).svg" },
  { name: "Marshall Islands", code: "MHL", file: "Marshall Islands (MHL).svg" },
  { name: "Martinique", code: "MTQ", file: "Martinique (MTQ).svg" },
  { name: "Mauritania", code: "MRT", file: "Mauritania (MRT).svg" },
  { name: "Mauritius", code: "MUS", file: "Mauritius (MUS).svg" },
  { name: "Mexico", code: "MEX", file: "Mexico (MEX).svg" },
  { name: "Micronesia", code: "FSM", file: "Micronesia (FSM).svg" },
  { name: "Moldova", code: "MDA", file: "Moldova (MDA).svg" },
  { name: "Monaco", code: "MCO", file: "Monaco (MCO).svg" },
  { name: "Mongolia", code: "MNG", file: "Mongolia (MNG).svg" },
  { name: "Monserrat", code: "MSR", file: "Monserrat (MSR).svg" },
  { name: "Montenegro", code: "MNE", file: "Montenegro (MNE).svg" },
  { name: "Morocco", code: "MAR", file: "Morocco (MAR).svg" },
  { name: "Mozambique", code: "MOZ", file: "Mozambique (MOZ).svg" },
  { name: "Myanmar", code: "MMR", file: "Myanmar (MMR).svg" },
  { name: "Namibia", code: "NAM", file: "Namibia (NAM).svg" },
  { name: "Nauru", code: "NRU", file: "Nauru (NRU).svg" },
  { name: "Nepal", code: "NPL", file: "Nepal (NPL).svg" },
  { name: "Netherlands", code: "NLD", file: "Netherlands (NLD).svg" },
  { name: "New Caledonia", code: "NCL", file: "New Caledonia (NCL).svg" },
  { name: "New Zealand", code: "NZL", file: "New Zealand (NZL).svg" },
  { name: "Nicaragua", code: "NIC", file: "Nicaragua (NIC).svg" },
  { name: "Niger", code: "NER", file: "Niger (NER).svg" },
  { name: "Nigeria", code: "NGA", file: "Nigeria (NGA).svg" },
  { name: "Niue", code: "NIU", file: "Niue (NIU).svg" },
  { name: "Norfolk Island", code: "NFK", file: "Norfolk Island (NFK).svg" },
  { name: "Northern Mariana Islands", code: "MNP", file: "Northern Mariana Islands (MNP).svg" },
  { name: "Norway", code: "NOR", file: "Norway (NOR).svg" },
  { name: "Occupied Palestinian Territory", code: "PSE", file: "Occupied Palestinian Territory (PSE).svg" },
  { name: "Oman", code: "OMN", file: "Oman (OMN).svg" },
  { name: "Pakistan", code: "PAK", file: "Pakistan (PAK).svg" },
  { name: "Palau", code: "PLW", file: "Palau (PLW).svg" },
  { name: "Panama", code: "PAN", file: "Panama (PAN).svg" },
  { name: "Papua New Guinea", code: "PNG", file: "Papua New Guinea (PNG).svg" },
  { name: "Paraguay", code: "PRY", file: "Paraguay (PRY).svg" },
  { name: "Peru", code: "PER", file: "Peru (PER).svg" },
  { name: "Philippines", code: "PHL", file: "Philippines (PHL).svg" },
  { name: "Pitcairn Islands", code: "PCN", file: "Pitcairn Islands (PCN).svg" },
  { name: "Poland", code: "POL", file: "Poland (POL).svg" },
  { name: "Portugal", code: "PRT", file: "Portugal (PRT).svg" },
  { name: "Private", code: "", file: "Private.svg" },
  { name: "Puerto Rico", code: "PRI", file: "Puerto Rico (PRI).svg" },
  { name: "Qatar", code: "QAT", file: "Qatar (QAT).svg" },
  { name: "Republic of Korea", code: "KOR", file: "Republic of Korea (KOR).svg" },
  { name: "Republic of North Macedonia", code: "MKD", file: "Republic of North Macedonia (MKD).svg" },
  { name: "Reunion", code: "REU", file: "Reunion (REU).svg" },
  { name: "Romania", code: "ROU", file: "Romania (ROU).svg" },
  { name: "Russian Federation", code: "RUS", file: "Russian Federation (RUS).svg" },
  { name: "Rwanda", code: "RWA", file: "Rwanda (RWA).svg" },
  { name: "Saint Helena", code: "SHN", file: "Saint Helena (SHN).svg" },
  { name: "Saint Kitts and Nevis", code: "KNA", file: "Saint Kitts and Nevis (KNA).svg" },
  { name: "Saint Lucia", code: "LCA", file: "Saint Lucia (LCA).svg" },
  { name: "Saint Vincent and the Grenadines", code: "VCT", file: "Saint Vincent and the Grenadines (VCT).svg" },
  { name: "Samoa", code: "WSM", file: "Samoa (WSM).svg" },
  { name: "San Marino", code: "SMR", file: "San Marino (SMR).svg" },
  { name: "Sao Tome and Principe", code: "STP", file: "Sao Tome and Principe (STP).svg" },
  { name: "Saudi Arabia", code: "SAU", file: "Saudi Arabia (SAU).svg" },
  { name: "Senegal", code: "SEN", file: "Senegal (SEN).svg" },
  { name: "Serbia", code: "SRB", file: "Serbia (SRB).svg" },
  { name: "Seychelles", code: "SYC", file: "Seychelles (SYC).svg" },
  { name: "Sierra Leone", code: "SLE", file: "Sierra Leone (SLE).svg" },
  { name: "Singapore", code: "SGP", file: "Singapore (SGP).svg" },
  { name: "Sint Maarten", code: "SXM", file: "Sint Maarten (SXM).svg" },
  { name: "Slovakia", code: "SVK", file: "Slovakia (SVK).svg" },
  { name: "Slovenia", code: "SVN", file: "Slovenia (SVN).svg" },
  { name: "Solomon Islands", code: "SLB", file: "Solomon Islands (SLB).svg" },
  { name: "Somalia", code: "SOM", file: "Somalia (SOM).svg" },
  { name: "South Africa", code: "ZAF", file: "South Africa (ZAF).svg" },
  { name: "South Australia", code: "", file: "South Australia.svg" },
  { name: "South Georgia and the South Sandwich Islands", code: "SGS", file: "South Georgia and the South Sandwich Islands (SGS).svg" },
  { name: "South Sudan", code: "SSD", file: "South Sudan (SSD).svg" },
  { name: "Sovereign Military Order of Malta", code: "", file: "Sovereign Military Order of Malta.svg" },
  { name: "Spain", code: "ESP", file: "Spain (ESP).svg" },
  { name: "Sri Lanka", code: "LKA", file: "Sri Lanka (LKA).svg" },
  { name: "Sudan", code: "SDN", file: "Sudan (SDN).svg" },
  { name: "Suriname", code: "SUR", file: "Suriname (SUR).svg" },
  { name: "Sweden", code: "SWE", file: "Sweden (SWE).svg" },
  { name: "Switzerland", code: "CHE", file: "Switzerland (CHE).svg" },
  { name: "Syrian Arab Republic", code: "SYR", file: "Syrian Arab Republic (SYR).svg" },
  { name: "Tajikistan", code: "TJK", file: "Tajikistan (TJK).svg" },
  { name: "Thailand", code: "THA", file: "Thailand (THA).svg" },
  { name: "Timor-Leste", code: "TLS", file: "Timor-Leste (TLS).svg" },
  { name: "Togo", code: "TGO", file: "Togo (TGO).svg" },
  { name: "Tokelau", code: "TKL", file: "Tokelau (TKL).svg" },
  { name: "Tonga", code: "TON", file: "Tonga (TON).svg" },
  { name: "Trinidad and Tobago", code: "TTO", file: "Trinidad and Tobago (TTO).svg" },
  { name: "Tunisia", code: "TUN", file: "Tunisia (TUN).svg" },
  { name: "Turkmenistan", code: "TKM", file: "Turkmenistan (TKM).svg" },
  { name: "Turks and Caico Islands", code: "TCA", file: "Turks and Caico Islands (TCA).svg" },
  { name: "Tuvalu", code: "TUV", file: "Tuvalu (TUV).svg" },
  { name: "Türkiye", code: "TUR", file: "Türkiye (TUR).svg" },
  { name: "Uganda", code: "UGA", file: "Uganda (UGA).svg" },
  { name: "Ukraine", code: "UKR", file: "Ukraine (UKR).svg" },
  { name: "United Arab Emirates", code: "ARE", file: "United Arab Emirates (ARE).svg" },
  { name: "United Kingdom", code: "GBR", file: "United Kingdom (GBR).svg" },
  { name: "United Nations Foundation", code: "", file: "United Nations Foundation.svg" },
  { name: "United Republic of Tanzania", code: "TZA", file: "United Republic of Tanzania (TZA).svg" },
  { name: "United States of America", code: "USA", file: "United States of America (USA).svg" },
  { name: "Uruguay", code: "URY", file: "Uruguay (URY).svg" },
  { name: "Uzbekistan", code: "UZB", file: "Uzbekistan (UZB).svg" },
  { name: "Vanuatu", code: "VUT", file: "Vanuatu (VUT).svg" },
  { name: "Viet Nam", code: "VNM", file: "Viet Nam (VNM).svg" },
  { name: "Virgin Islands", code: "VIR", file: "Virgin Islands (VIR).svg" },
  { name: "Yemen", code: "YEM", file: "Yemen (YEM).svg" },
  { name: "Zambia", code: "ZMB", file: "Zambia (ZMB).svg" },
  { name: "Zimbabwe", code: "ZWE", file: "Zimbabwe (ZWE).svg" }
];
